### ISSUE TITLE
go-imap-compress does not work with latest go-imap

### ISSUE THREAD

**Issue by hartshorne** [emersion/go-imap-compress#3]
go-imap-compress deadlocks since https://github.com/emersion/go-imap/commit/ba92a48ae62c3d26cf99af90b38ec80dbab08b2d

tested against fastmail's IMAP server which supports COMPRESS=DEFLATE.
### client.go

```
package main

import (
  "crypto/tls"
  "log"
  "os"
  "os/signal"
  "runtime"
  "syscall"

  compress "github.com/emersion/go-imap-compress"
  client "github.com/emersion/go-imap/client"
)

func main() {
  go func() {
    sigs := make(chan os.Signal, 1)
    signal.Notify(sigs, syscall.SIGINT)
    buf := make([]byte, 1<<20)
    for {
      <-sigs
      stacklen := runtime.Stack(buf, true)
      log.Printf("=== received SIGINT ===\n*** goroutine dump...\n%s\n*** end\n", buf[:stacklen])
      os.Exit(1)
    }
  }()

  c, _ := client.DialTLS(
    "mail.messagingengine.com:993",
    &tls.Config{ServerName: "mail.messagingengine.com"},
  )
  c.SetDebug(os.Stderr)

  _ = c.Login("username@fastmail.com", "password")

  comp := compress.NewClient(c)
  if comp.SupportsCompression(compress.Deflate) {
    if err := comp.Compress(compress.Deflate); err != nil {
      log.Fatal(err)
    }
  }

  mbox, _ := c.Select("INBOX", false)
  log.Println("Flags for INBOX:", mbox.Flags)
}
```

this waits forever, the output with stack trace looks something like:

```
kzZSvw COMPRESS DEFLATE
kzZSvw OK DEFLATE active
wffn1Q SELECT INBOX
^C2016/09/27 16:09:54 === received SIGINT ===
*** goroutine dump...
goroutine 6 [running]:
main.main.func1()
  /Users/beau/Desktop/fast.go:22 +0x16a
created by main.main
  /Users/beau/Desktop/fast.go:26 +0x52

goroutine 1 [chan receive]:
github.com/emersion/go-imap/client.(*Client).execute(0xc4203dcdc0, 0x29c7a0, 0xc420445480, 0x29c7e0, 0xc42002e050, 0x0, 0x0, 0x0)
  /Users/beau/go/src/github.com/emersion/go-imap/client/client.go:183 +0x1c6
github.com/emersion/go-imap/client.(*Client).Select(0xc4203dcdc0, 0x1d83b4, 0x5, 0x0, 0x0, 0xc4201e1eb0, 0x10)
  /Users/beau/go/src/github.com/emersion/go-imap/client/cmd_auth.go:36 +0x17f
main.main()
  /Users/beau/Desktop/fast.go:43 +0x1fc

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
  /usr/local/Cellar/go/1.7.1/libexec/src/runtime/asm_amd64.s:2086 +0x1

goroutine 5 [syscall]:
os/signal.signal_recv(0x29e720)
  /usr/local/Cellar/go/1.7.1/libexec/src/runtime/sigqueue.go:116 +0x157
os/signal.loop()
  /usr/local/Cellar/go/1.7.1/libexec/src/os/signal/signal_unix.go:22 +0x22
created by os/signal.init.1
  /usr/local/Cellar/go/1.7.1/libexec/src/os/signal/signal_unix.go:28 +0x41

goroutine 18 [select, locked to thread]:
runtime.gopark(0x1efeb8, 0x0, 0x1d86f4, 0x6, 0x18, 0x2)
  /usr/local/Cellar/go/1.7.1/libexec/src/runtime/proc.go:259 +0x13a
runtime.selectgoImpl(0xc420026730, 0x0, 0x18)
  /usr/local/Cellar/go/1.7.1/libexec/src/runtime/select.go:423 +0x11d9
runtime.selectgo(0xc420026730)
  /usr/local/Cellar/go/1.7.1/libexec/src/runtime/select.go:238 +0x1c
runtime.ensureSigM.func1()
  /usr/local/Cellar/go/1.7.1/libexec/src/runtime/signal1_unix.go:304 +0x2d1
runtime.goexit()
  /usr/local/Cellar/go/1.7.1/libexec/src/runtime/asm_amd64.s:2086 +0x1

goroutine 50 [chan receive]:
github.com/emersion/go-imap/client.(*Client).handleContinuationReqs(0xc4203dcdc0, 0xc4204c4c60)
  /Users/beau/go/src/github.com/emersion/go-imap/client/client.go:224 +0xe2
created by github.com/emersion/go-imap/client.New
  /Users/beau/go/src/github.com/emersion/go-imap/client/client.go:413 +0x328

goroutine 51 [chan receive]:
github.com/emersion/go-imap/client.(*Client).handleUnilateral(0xc4203dcdc0)
  /Users/beau/go/src/github.com/emersion/go-imap/client/client.go:258 +0x13f
created by github.com/emersion/go-imap/client.New
  /Users/beau/go/src/github.com/emersion/go-imap/client/client.go:414 +0x34a

goroutine 52 [IO wait]:
net.runtime_pollWait(0x3aef00, 0x72, 0x5)
  /usr/local/Cellar/go/1.7.1/libexec/src/runtime/netpoll.go:160 +0x59
net.(*pollDesc).wait(0xc42005a140, 0x72, 0xc42003d6c0, 0xc42000c1f8)
  /usr/local/Cellar/go/1.7.1/libexec/src/net/fd_poll_runtime.go:73 +0x38
net.(*pollDesc).waitRead(0xc42005a140, 0x29d620, 0xc42000c1f8)
  /usr/local/Cellar/go/1.7.1/libexec/src/net/fd_poll_runtime.go:78 +0x34
net.(*netFD).Read(0xc42005a0e0, 0xc420031400, 0x400, 0x400, 0x0, 0x29d620, 0xc42000c1f8)
  /usr/local/Cellar/go/1.7.1/libexec/src/net/fd_unix.go:243 +0x1a1
net.(*conn).Read(0xc42002e030, 0xc420031400, 0x400, 0x400, 0x0, 0x0, 0x0)
  /usr/local/Cellar/go/1.7.1/libexec/src/net/net.go:173 +0x70
crypto/tls.(*block).readFromUntil(0xc420016900, 0x3aefc0, 0xc42002e030, 0x5, 0xc42002e030, 0xc420076f50)
  /usr/local/Cellar/go/1.7.1/libexec/src/crypto/tls/conn.go:472 +0x91
crypto/tls.(*Conn).readRecord(0xc420076e00, 0x1eff17, 0xc420076f00, 0x878b5)
  /usr/local/Cellar/go/1.7.1/libexec/src/crypto/tls/conn.go:574 +0xc4
crypto/tls.(*Conn).Read(0xc420076e00, 0xc42052a000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
  /usr/local/Cellar/go/1.7.1/libexec/src/crypto/tls/conn.go:1109 +0x116
bufio.(*Reader).fill(0xc4204c5440)
  /usr/local/Cellar/go/1.7.1/libexec/src/bufio/bufio.go:97 +0x10c
bufio.(*Reader).ReadByte(0xc4204c5440, 0x0, 0xc42003db18, 0x10000000000e278)
  /usr/local/Cellar/go/1.7.1/libexec/src/bufio/bufio.go:231 +0x51
compress/flate.(*decompressor).moreBits(0xc420524000, 0x34c0d0, 0x1068e)
  /usr/local/Cellar/go/1.7.1/libexec/src/compress/flate/inflate.go:690 +0x37
compress/flate.(*decompressor).nextBlock(0xc420524000)
  /usr/local/Cellar/go/1.7.1/libexec/src/compress/flate/inflate.go:302 +0x39
compress/flate.(*decompressor).Read(0xc420524000, 0xc420522000, 0x1000, 0x1000, 0xc42003dc80, 0xc41ffddd64, 0xc42003dc48)
  /usr/local/Cellar/go/1.7.1/libexec/src/compress/flate/inflate.go:346 +0x5e
github.com/emersion/go-imap-compress.(*conn).Read(0xc4204225d0, 0xc420522000, 0x1000, 0x1000, 0xffffffffffffffff, 0x10, 0x18)
  /Users/beau/go/src/github.com/emersion/go-imap-compress/deflate.go:17 +0x52
io.(*teeReader).Read(0xc420445440, 0xc420522000, 0x1000, 0x1000, 0xc420420a00, 0xc42003dc78, 0x10eb8)
  /usr/local/Cellar/go/1.7.1/libexec/src/io/io.go:523 +0x55
bufio.(*Reader).fill(0xc4204c4cc0)
  /usr/local/Cellar/go/1.7.1/libexec/src/bufio/bufio.go:97 +0x10c
bufio.(*Reader).ReadRune(0xc4204c4cc0, 0xfe7, 0xc420420a01, 0xe, 0xc42003dd48)
  /usr/local/Cellar/go/1.7.1/libexec/src/bufio/bufio.go:262 +0xad
github.com/emersion/go-imap.(*Reader).ReadAtom(0xc420422570, 0x1efe78, 0xc400000002, 0xc42047e400, 0xee1b)
  /Users/beau/go/src/github.com/emersion/go-imap/read.go:161 +0x5e
github.com/emersion/go-imap.ReadResp(0xc420422570, 0xc4204c4e40, 0x0, 0x0, 0x0)
  /Users/beau/go/src/github.com/emersion/go-imap/response.go:64 +0x43
github.com/emersion/go-imap/client.(*Client).read(0xc4203dcdc0, 0xc4204c4e40, 0x0, 0x0)
  /Users/beau/go/src/github.com/emersion/go-imap/client/client.go:89 +0xee
created by github.com/emersion/go-imap/client.(*Client).handleUnilateral
  /Users/beau/go/src/github.com/emersion/go-imap/client/client.go:256 +0x102

goroutine 53 [chan receive]:
github.com/emersion/go-imap/responses.(*Select).HandleFrom(0xc42002e050, 0xc4204c5500, 0x0, 0x0)
  /Users/beau/go/src/github.com/emersion/go-imap/responses/select.go:18 +0x84
github.com/emersion/go-imap/client.(*Client).execute.func1(0xc4204c5560, 0x29c7e0, 0xc42002e050, 0xc42002e058)
  /Users/beau/go/src/github.com/emersion/go-imap/client/client.go:174 +0x42
created by github.com/emersion/go-imap/client.(*Client).execute
  /Users/beau/go/src/github.com/emersion/go-imap/client/client.go:180 +0x43b

*** end
exit status 1
```

removing this code:

```
  comp := compress.NewClient(c)
  if comp.SupportsCompression(compress.Deflate) {
    if err := comp.Compress(compress.Deflate); err != nil {
      log.Fatal(err)
    }
  }
```

outputs this:

```
tEp8pA SELECT INBOX
* 5 EXISTS
* 0 RECENT
* FLAGS (\Answered \Flagged \Draft \Deleted \Seen $X-ME-Annot-2 $IsMailingList $IsNotification $HasAttachment $HasTD $IsTrusted)
* OK [PERMANENTFLAGS (\Answered \Flagged \Draft \Deleted \Seen $X-ME-Annot-2 $IsMailingList $IsNotification $HasAttachment $HasTD $IsTrusted \*)] Ok
* OK [UIDVALIDITY 1464806015] Ok
* OK [UIDNEXT 10] Ok
* OK [HIGHESTMODSEQ 65] Ok
* OK [URLMECH INTERNAL] Ok
* OK [ANNOTATIONS 65536] Ok
tEp8pA OK [READ-WRITE] Completed
imap/client: 2016/09/27 16:11:20 response has not been handled:  &{* OK HIGHESTMODSEQ [65] Ok}
imap/client: 2016/09/27 16:11:20 response has not been handled:  &{* OK URLMECH [INTERNAL] Ok}
imap/client: 2016/09/27 16:11:20 response has not been handled:  &{* OK ANNOTATIONS [65536] Ok}
2016/09/27 16:11:20 Flags for INBOX: [\Answered \Flagged \Draft \Deleted \Seen $X-ME-Annot-2 $IsMailingList $IsNotification $HasAttachment $HasTD $IsTrusted]
```

the last revision of go-imap to work is https://github.com/emersion/go-imap/commit/ebd8ee9fbeb2392d3f83e2b6433aa9f2f295bd82 (which builds against https://github.com/emersion/go-imap-compress/commit/e0a20ded6a2df940a3dee1fb8ffe4c92f10930c3). the output of client.go from above (without .SetDebug) is:

```
2016/09/27 16:14:49 Response has not been handled &{* OK HIGHESTMODSEQ [65] Ok}
2016/09/27 16:14:49 Response has not been handled &{* OK URLMECH [INTERNAL] Ok}
2016/09/27 16:14:49 Response has not been handled &{* OK ANNOTATIONS [65536] Ok}
2016/09/27 16:14:49 Flags for INBOX: [\Answered \Flagged \Draft \Deleted \Seen $X-ME-Annot-2 $IsMailingList $IsNotification $HasAttachment $HasTD $IsTrusted]
```

**Comment by emersion** [comment]
Thanks for reporting this issue! It's now fixed.

Pro-tip©: you can press <kbd>Ctrl</kbd> + <kbd>\\</kbd> to stop the process and get a stack trace ;-)
